management:
  security:
    enabled: false
server:
    ssl:
      key-store: classpath:keystore.jks
      key-store-password: changeit
      key-store-type: JKS
      key-alias: linkedin
      key-password: changeit
---
spring:
  profiles: dev
server:
  port: 8000

---
spring:
  profiles: test
server:
  port: 9000
